//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AHP.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriteriaComparison
    {
        public System.Guid CriteriaID1 { get; set; }
        public System.Guid CriteriaID2 { get; set; }
        public double CriteriaRatio { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
    
        public virtual Criterion Criterion { get; set; }
        public virtual Criterion Criterion1 { get; set; }
    }
}
